### ISSUE TITLE
session keys are on top level folder

### ISSUE THREAD

**Issue by uharband** [foundation-runtime/cluster#13]
the keys used for locking the sessions are all in the consul KV top level. it would be nice to have them all under a logical structure, e.g. "master-slave/component-name" to get:
master-slave/pps/housekeeping
master-slave/upm/housekeeping

**Comment by yairogen** [comment]
so - we'll use this convention:
/master-slave/component-name/job-name

would that work for you?

**Comment by uharband** [comment]
Sounds great. Thanks for the prompt response!

**Comment by igreenfield** [comment]
I think it is very good

**Comment by nahsh** [comment]
makes sence
