### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by binyaf** [foundation-runtime/cluster#7]
We need to support user override on default configuration for mongo servers.
If user (for some reason) will want to have his application mongo-db on host a, and his library mongo-db on host b.
So since anyway not all applications have the same configuration for mongo-db host&port, I think the mongo host&port config of the library needs to be meaningful (e.g. master-slave.mongoDB.1.port)

**Comment by yairogen** [comment]
I see 2 options:

1. add API to inject into the library the prefix name you want the library to use for the mongo servers.
2. add API that gets the host and port list as Objects. In this case the library will not look for the mongo servers in the config at all.

Which of the above sounds right for you?

**Comment by binyaf** [comment]
what's wrong about:
master-slave.mongoDB.1.host = <host>
master-slave.mongoDB.1.port = <port>

If not, I prefer 2. I think it's better. all the 'prefix' stuff is confusing

**Comment by igreenfield** [comment]
I vote for 1 and if the library get empty prefix it will fall back to mongodb.1 ....

**Comment by yairogen** [comment]
@igreenfield @binyaf  ill supporting both approaches be too confusing?

**Comment by binyaf** [comment]
both is the best!

**Comment by yairogen** [comment]
ok. i'll work on both. if no new API is called it will be the same as today.

**Comment by yairogen** [comment]
fixed in pull #8
