### ISSUE TITLE
Require consul configuration compatibilty with jersey-core 1.18.3

### ISSUE THREAD

**Issue by bahirsch** [foundation-runtime/cluster#9]
Wiki page indicates that for consul configuration, the requirement for javax.ws.rs:javax.ws.rs-api:2.0.1 must be satisfied. 
Should work with versions prior to 2.0.1; as it is not always possible to satisfy the requirement due to other dependencies with high priorities.

**Comment by yairogen** [comment]
This is a constraint from the Consul Client:
https://github.com/OrbitzWorldwide/consul-client/blob/master/build.gradle

**Comment by yairogen** [comment]
latest version now support pure apache http client and we no longer use consul client. 
this eliminates this issue.
closing...
